# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class TourismEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file_path: str = Field(
        ...,
        description="Path to the file to load. Supported formats: .parquet, .geoparquet, .geojson, .json, .gpkg, .csv, .shp",
        title="File Path",
    )
    layer: str | None = Field(
        None,
        description="Layer name for GeoPackage files (optional, only used for .gpkg files)",
        title="Layer",
    )


class GuestTable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    columns: list[str] | None = Field(
        None,
        description="The list of dataframe columns to render in the table. Leave empty to render all columns",
        title="Columns",
    )


class DashboardWidgets(BaseModel):
    guest_table: GuestTable | None = Field(None, title="Draw Guest Summary Table")


class TourismReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    template_path: str = Field(
        ...,
        description="Path or URL to the Word template (.docx) file with Jinja2 placeholders. Supports local paths and remote URLs (http://, https://).",
        title="Template Path",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class Aggregator(str, Enum):
    sum = "sum"
    count_ = "count"
    min = "min"
    max = "max"
    mean = "mean"
    unique = "unique"
    nunique = "nunique"
    median = "median"
    night_day_ratio = "night_day_ratio"


class Unit(str, Enum):
    m = "m"
    km = "km"
    s = "s"
    h = "h"
    d = "d"
    m_s = "m/s"
    km_h = "km/h"


class AggFunc(str, Enum):
    sum = "sum"
    count_ = "count"
    min = "min"
    max = "max"
    mean = "mean"
    unique = "unique"
    nunique = "nunique"
    median = "median"
    night_day_ratio = "night_day_ratio"


class PlotCategoryStyle(BaseModel):
    marker_color: str | None = Field(None, title="Marker Color")
    textposition: str | None = Field(None, title="Textposition")
    texttemplate: str | None = Field(None, title="Texttemplate")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class SummaryParam(BaseModel):
    display_name: str = Field(..., title="Display Name")
    aggregator: Aggregator = Field(..., title="Aggregator")
    column: str | None = Field(None, title="Column")
    original_unit: Unit | None = Field(None, title="Original Unit")
    new_unit: Unit | None = Field(None, title="New Unit")
    decimal_places: int | None = Field(2, title="Decimal Places")


class BarConfig(BaseModel):
    column: str = Field(
        ..., description="The dataframe column to aggregate.", title="Column"
    )
    agg_func: AggFunc = Field(
        ..., description="The aggregate function to apply.", title="Agg Func"
    )
    label: str = Field(
        ..., description="The label for the bar in the chart legend.", title="Label"
    )
    show_label: bool | None = Field(
        False,
        description="Whether to show the value label on top of the bar.",
        title="Show Label",
    )
    style: PlotCategoryStyle | None = Field(
        None, description="The style parameters for the category", title="Style"
    )


class GuestSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary_params: list[SummaryParam] = Field(
        default_factory=lambda: [
            SummaryParam.model_validate(v)
            for v in [
                {
                    "display_name": "Non Resident Adults",
                    "aggregator": "sum",
                    "column": "nra",
                },
                {
                    "display_name": "Non Resident Children",
                    "aggregator": "sum",
                    "column": "nrc",
                },
                {
                    "display_name": "Non Resident Students",
                    "aggregator": "sum",
                    "column": "nrs",
                },
                {"display_name": "Citizen Adults", "aggregator": "sum", "column": "ca"},
                {
                    "display_name": "Citizen Children",
                    "aggregator": "sum",
                    "column": "cc",
                },
                {
                    "display_name": "Citizen Students",
                    "aggregator": "sum",
                    "column": "cs",
                },
                {
                    "display_name": "Resident Adults",
                    "aggregator": "sum",
                    "column": "ra",
                },
                {
                    "display_name": "Resident Children",
                    "aggregator": "sum",
                    "column": "rc",
                },
                {
                    "display_name": "Resident Students",
                    "aggregator": "sum",
                    "column": "rs",
                },
                {"display_name": "Narok Adults", "aggregator": "sum", "column": "na"},
                {"display_name": "Narok Children", "aggregator": "sum", "column": "nc"},
                {"display_name": "Narok Students", "aggregator": "sum", "column": "ns"},
            ]
        ],
        description="The parameters that define how to calculate summary statistics.",
        title="Summary Params",
    )


class GuestGroupBar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bar_chart_configs: list[BarConfig] = Field(
        default_factory=lambda: [
            BarConfig.model_validate(v)
            for v in [
                {
                    "column": "Non Resident Adults",
                    "agg_func": "sum",
                    "label": "Non Resident Adults",
                },
                {
                    "column": "Non Resident Children",
                    "agg_func": "sum",
                    "label": "Non Resident Children",
                },
                {
                    "column": "Non Resident Students",
                    "agg_func": "sum",
                    "label": "Non Resident Students",
                },
                {
                    "column": "Resident Adults",
                    "agg_func": "sum",
                    "label": "Resident Adults",
                },
                {
                    "column": "Resident Children",
                    "agg_func": "sum",
                    "label": "Resident Children",
                },
                {
                    "column": "Resident Students",
                    "agg_func": "sum",
                    "label": "Resident Students",
                },
                {
                    "column": "Citizen Adults",
                    "agg_func": "sum",
                    "label": "Citizen Adults",
                },
                {
                    "column": "Citizen Children",
                    "agg_func": "sum",
                    "label": "Citizen Children",
                },
                {
                    "column": "Citizen Students",
                    "agg_func": "sum",
                    "label": "Citizen Students",
                },
                {"column": "Narok Adults", "agg_func": "sum", "label": "Narok Adults"},
                {
                    "column": "Narok Children",
                    "agg_func": "sum",
                    "label": "Narok Children",
                },
                {
                    "column": "Narok Students",
                    "agg_func": "sum",
                    "label": "Narok Students",
                },
            ]
        ],
        description="Bar chart configuration.",
        title="Bar Chart Configuration",
    )


class GuestGateBar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bar_chart_configs: list[BarConfig] = Field(
        default_factory=lambda: [
            BarConfig.model_validate(v)
            for v in [
                {
                    "column": "Paying Guests",
                    "agg_func": "sum",
                    "label": "Paying Guests",
                    "show_label": True,
                },
                {
                    "column": "Narok County Government(NCG) Guests",
                    "agg_func": "sum",
                    "label": "Narok County Government(NCG) Guests",
                    "show_label": True,
                },
            ]
        ],
        description="Bar chart configuration.",
        title="Bar Chart Configuration",
    )


class GuestEntry(BaseModel):
    guest_summary: GuestSummary | None = Field(None, title="Summarize Guest Entry")
    guest_group_bar: GuestGroupBar | None = Field(
        None, title="Draw Guest Entry by Group Chart"
    )
    guest_gate_bar: GuestGateBar | None = Field(
        None, title="Draw Guest Entry by Gate Chart"
    )


class VehicleGateBar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bar_chart_configs: list[BarConfig] = Field(
        default_factory=lambda: [
            BarConfig.model_validate(v)
            for v in [
                {
                    "column": "paying",
                    "agg_func": "sum",
                    "label": "Paying Vehicles",
                    "show_label": True,
                },
                {
                    "column": "nonpaying",
                    "agg_func": "sum",
                    "label": "Non-Paying Vehicles",
                    "show_label": True,
                },
                {
                    "column": "sticker",
                    "agg_func": "sum",
                    "label": "Annual Sticker",
                    "show_label": True,
                },
            ]
        ],
        description="Bar chart configuration.",
        title="Bar Chart Configuration",
    )


class VehicleEntry(BaseModel):
    vehicle_gate_bar: VehicleGateBar | None = Field(
        None, title="Draw Vehicle Entry by Gate Chart"
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    tourism_events: TourismEvents | None = Field(None, title="Load Tourism Events")
    Guest_Entry: GuestEntry | None = Field(
        None,
        alias="Guest Entry",
        description="Process guest entry events: categorize, summarize, and chart.",
    )
    Vehicle_Entry: VehicleEntry | None = Field(
        None,
        alias="Vehicle Entry",
        description="Process vehicle entry events and generate chart.",
    )
    Dashboard_Widgets: DashboardWidgets | None = Field(
        None,
        alias="Dashboard Widgets",
        description="Create chart and table widgets for the dashboard.",
    )
    tourism_report: TourismReport | None = Field(None, title="Create Tourism Report")
