# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mt Tourism
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_bar_chart as draw_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_mt.tasks import mt_guest_entry as mt_guest_entry
from ecoscope_workflows_ext_mt.tasks import mt_guest_entry_pivot as mt_guest_entry_pivot

# %% [markdown]
# ## Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Extract Timezone

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## Load Tourism Events

# %%
# parameters

tourism_events_params = dict(
    file_path=...,
    layer=...,
)

# %%
# call the task


tourism_events = (
    load_df.set_task_instance_id("tourism_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(deserialize_json=True, **tourism_events_params)
    .call()
)


# %% [markdown]
# ## Filter Guest Entry Events

# %%
# parameters

filter_guest_params = dict()

# %%
# call the task


filter_guest = (
    filter_row_values.set_task_instance_id("filter_guest")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=tourism_events,
        column="event_type",
        values=["guest_entry"],
        **filter_guest_params,
    )
    .call()
)


# %% [markdown]
# ## Process Guest Entry

# %%
# parameters

guest_entry_data_params = dict()

# %%
# call the task


guest_entry_data = (
    mt_guest_entry.set_task_instance_id("guest_entry_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=filter_guest, **guest_entry_data_params)
    .call()
)


# %% [markdown]
# ## Summarize Guest Entry

# %%
# parameters

guest_summary_params = dict(
    summary_params=...,
)

# %%
# call the task


guest_summary = (
    summarize_df.set_task_instance_id("guest_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=guest_entry_data,
        groupby_cols=["guest_group"],
        reset_index=True,
        **guest_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Guest Entry Pivot by Gate

# %%
# parameters

guest_pivot_params = dict()

# %%
# call the task


guest_pivot = (
    mt_guest_entry_pivot.set_task_instance_id("guest_pivot")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=guest_entry_data, **guest_pivot_params)
    .call()
)


# %% [markdown]
# ## Draw Guest Entry by Group Chart

# %%
# parameters

guest_group_bar_params = dict(
    bar_chart_configs=...,
    widget_id=...,
)

# %%
# call the task


guest_group_bar = (
    draw_bar_chart.set_task_instance_id("guest_group_bar")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=guest_summary,
        category="guest_group",
        layout_kwargs=None,
        **guest_group_bar_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Guest Group Chart

# %%
# parameters

persist_guest_group_bar_params = dict(
    filename=...,
)

# %%
# call the task


persist_guest_group_bar = (
    persist_text.set_task_instance_id("persist_guest_group_bar")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=guest_group_bar,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="guest_group_bar",
        **persist_guest_group_bar_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Guest Entry by Gate Chart

# %%
# parameters

guest_gate_bar_params = dict(
    bar_chart_configs=...,
    widget_id=...,
)

# %%
# call the task


guest_gate_bar = (
    draw_bar_chart.set_task_instance_id("guest_gate_bar")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=guest_pivot,
        category="gate",
        layout_kwargs=None,
        **guest_gate_bar_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Guest Gate Chart

# %%
# parameters

persist_guest_gate_bar_params = dict(
    filename=...,
)

# %%
# call the task


persist_guest_gate_bar = (
    persist_text.set_task_instance_id("persist_guest_gate_bar")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=guest_gate_bar,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="guest_gate_bar",
        **persist_guest_gate_bar_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Vehicle Entry Events

# %%
# parameters

filter_vehicle_params = dict()

# %%
# call the task


filter_vehicle = (
    filter_row_values.set_task_instance_id("filter_vehicle")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=tourism_events,
        column="event_type",
        values=["vehicle_entry"],
        **filter_vehicle_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Vehicle Entry by Gate Chart

# %%
# parameters

vehicle_gate_bar_params = dict(
    bar_chart_configs=...,
    widget_id=...,
)

# %%
# call the task


vehicle_gate_bar = (
    draw_bar_chart.set_task_instance_id("vehicle_gate_bar")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=filter_vehicle,
        category="gate",
        layout_kwargs=None,
        **vehicle_gate_bar_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Vehicle Gate Chart

# %%
# parameters

persist_vehicle_gate_bar_params = dict(
    filename=...,
)

# %%
# call the task


persist_vehicle_gate_bar = (
    persist_text.set_task_instance_id("persist_vehicle_gate_bar")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=vehicle_gate_bar,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="vehicle_gate_bar",
        **persist_vehicle_gate_bar_params,
    )
    .call()
)


# %% [markdown]
# ## Set Guest Group Chart Title

# %%
# parameters

set_guest_group_title_params = dict()

# %%
# call the task


set_guest_group_title = (
    set_string_var.set_task_instance_id("set_guest_group_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Guest Entry by Group", **set_guest_group_title_params)
    .call()
)


# %% [markdown]
# ## Create Guest Group Chart Widget

# %%
# parameters

guest_group_widget_params = dict(
    view=...,
)

# %%
# call the task


guest_group_widget = (
    create_plot_widget_single_view.set_task_instance_id("guest_group_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title=set_guest_group_title,
        data=persist_guest_group_bar,
        **guest_group_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Set Guest Gate Chart Title

# %%
# parameters

set_guest_gate_title_params = dict()

# %%
# call the task


set_guest_gate_title = (
    set_string_var.set_task_instance_id("set_guest_gate_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Guest Entry by Gate", **set_guest_gate_title_params)
    .call()
)


# %% [markdown]
# ## Create Guest Gate Chart Widget

# %%
# parameters

guest_gate_widget_params = dict(
    view=...,
)

# %%
# call the task


guest_gate_widget = (
    create_plot_widget_single_view.set_task_instance_id("guest_gate_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title=set_guest_gate_title,
        data=persist_guest_gate_bar,
        **guest_gate_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Set Vehicle Chart Title

# %%
# parameters

set_vehicle_title_params = dict()

# %%
# call the task


set_vehicle_title = (
    set_string_var.set_task_instance_id("set_vehicle_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Vehicle Entry by Gate", **set_vehicle_title_params)
    .call()
)


# %% [markdown]
# ## Create Vehicle Chart Widget

# %%
# parameters

vehicle_widget_params = dict(
    view=...,
)

# %%
# call the task


vehicle_widget = (
    create_plot_widget_single_view.set_task_instance_id("vehicle_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title=set_vehicle_title, data=persist_vehicle_gate_bar, **vehicle_widget_params
    )
    .call()
)


# %% [markdown]
# ## Set Table Title

# %%
# parameters

set_table_title_params = dict()

# %%
# call the task


set_table_title = (
    set_string_var.set_task_instance_id("set_table_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Guest Entry Summary", **set_table_title_params)
    .call()
)


# %% [markdown]
# ## Draw Guest Summary Table

# %%
# parameters

guest_table_params = dict(
    columns=...,
)

# %%
# call the task


guest_table = (
    draw_table.set_task_instance_id("guest_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=guest_summary,
        table_config={"enable_sorting": True},
        widget_id=set_table_title,
        **guest_table_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Guest Table

# %%
# parameters

persist_guest_table_params = dict(
    filename=...,
)

# %%
# call the task


persist_guest_table = (
    persist_text.set_task_instance_id("persist_guest_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=guest_table,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="guest_summary_table",
        **persist_guest_table_params,
    )
    .call()
)


# %% [markdown]
# ## Create Table Widget

# %%
# parameters

table_widget_params = dict(
    view=...,
)

# %%
# call the task


table_widget = (
    create_table_widget_single_view.set_task_instance_id("table_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=set_table_title, data=persist_guest_table, **table_widget_params)
    .call()
)


# %% [markdown]
# ## Export Guest Summary

# %%
# parameters

persist_guest_csv_params = dict(
    filename=...,
)

# %%
# call the task


persist_guest_csv = (
    persist_df_wrapper.set_task_instance_id("persist_guest_csv")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        df=guest_summary,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="guest_entry_summary",
        filetypes=["csv"],
        sanitize=False,
        **persist_guest_csv_params,
    )
    .call()
)


# %% [markdown]
# ## Create Tourism Report

# %%
# parameters

tourism_report_params = dict(
    template_path=...,
)

# %%
# call the task


tourism_report = (
    create_docx.set_task_instance_id("tourism_report")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        groupers=None,
        context={
            "items": [
                {
                    "item_type": "timerange",
                    "key": "report_date",
                    "value": time_range,
                    "format": "%b %Y",
                },
                {
                    "item_type": "image",
                    "key": "guest_entry_bar_chart",
                    "value": persist_guest_group_bar,
                    "screenshot_config": {
                        "wait_for_timeout": 0,
                        "max_concurrent_pages": 2,
                    },
                },
                {
                    "item_type": "image",
                    "key": "guest_entry_bar_gate",
                    "value": persist_guest_gate_bar,
                    "screenshot_config": {
                        "wait_for_timeout": 0,
                        "max_concurrent_pages": 2,
                    },
                },
                {
                    "item_type": "image",
                    "key": "vehicle_entry_bar",
                    "value": persist_vehicle_gate_bar,
                    "screenshot_config": {
                        "wait_for_timeout": 0,
                        "max_concurrent_pages": 2,
                    },
                },
                {"item_type": "table", "key": "data", "value": guest_summary},
            ]
        },
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="mt_tourism_report",
        **tourism_report_params,
    )
    .call()
)


# %% [markdown]
# ## Create Dashboard

# %%
# parameters

dashboard_params = dict(
    groupers=...,
    warning=...,
)

# %%
# call the task


dashboard = (
    gather_dashboard.set_task_instance_id("dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[guest_group_widget, guest_gate_widget, vehicle_widget, table_widget],
        time_range=time_range,
        **dashboard_params,
    )
    .call()
)
