# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_bar_chart as draw_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_mt.tasks import mt_guest_entry as mt_guest_entry
from ecoscope_workflows_ext_mt.tasks import mt_guest_entry_pivot as mt_guest_entry_pivot

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    get_timezone = (
        get_timezone_from_time_range.validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params_dict.get("get_timezone") or {}))
        .call()
    )

    tourism_events = (
        load_df.validate()
        .set_task_instance_id("tourism_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(deserialize_json=True, **(params_dict.get("tourism_events") or {}))
        .call()
    )

    filter_guest = (
        filter_row_values.validate()
        .set_task_instance_id("filter_guest")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=tourism_events,
            column="event_type",
            values=["guest_entry"],
            **(params_dict.get("filter_guest") or {}),
        )
        .call()
    )

    guest_entry_data = (
        mt_guest_entry.validate()
        .set_task_instance_id("guest_entry_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=filter_guest, **(params_dict.get("guest_entry_data") or {}))
        .call()
    )

    guest_summary = (
        summarize_df.validate()
        .set_task_instance_id("guest_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=guest_entry_data,
            groupby_cols=["guest_group"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Non Resident Adults",
                    "aggregator": "sum",
                    "column": "nra",
                },
                {
                    "display_name": "Non Resident Children",
                    "aggregator": "sum",
                    "column": "nrc",
                },
                {
                    "display_name": "Non Resident Students",
                    "aggregator": "sum",
                    "column": "nrs",
                },
                {"display_name": "Citizen Adults", "aggregator": "sum", "column": "ca"},
                {
                    "display_name": "Citizen Children",
                    "aggregator": "sum",
                    "column": "cc",
                },
                {
                    "display_name": "Citizen Students",
                    "aggregator": "sum",
                    "column": "cs",
                },
                {
                    "display_name": "Resident Adults",
                    "aggregator": "sum",
                    "column": "ra",
                },
                {
                    "display_name": "Resident Children",
                    "aggregator": "sum",
                    "column": "rc",
                },
                {
                    "display_name": "Resident Students",
                    "aggregator": "sum",
                    "column": "rs",
                },
                {"display_name": "Narok Adults", "aggregator": "sum", "column": "na"},
                {"display_name": "Narok Children", "aggregator": "sum", "column": "nc"},
                {"display_name": "Narok Students", "aggregator": "sum", "column": "ns"},
            ],
            **(params_dict.get("guest_summary") or {}),
        )
        .call()
    )

    guest_pivot = (
        mt_guest_entry_pivot.validate()
        .set_task_instance_id("guest_pivot")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=guest_entry_data, **(params_dict.get("guest_pivot") or {}))
        .call()
    )

    guest_group_bar = (
        draw_bar_chart.validate()
        .set_task_instance_id("guest_group_bar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=guest_summary,
            category="guest_group",
            layout_kwargs=None,
            bar_chart_configs=[
                {
                    "column": "Non Resident Adults",
                    "agg_func": "sum",
                    "label": "Non Resident Adults",
                },
                {
                    "column": "Non Resident Children",
                    "agg_func": "sum",
                    "label": "Non Resident Children",
                },
                {
                    "column": "Non Resident Students",
                    "agg_func": "sum",
                    "label": "Non Resident Students",
                },
                {
                    "column": "Resident Adults",
                    "agg_func": "sum",
                    "label": "Resident Adults",
                },
                {
                    "column": "Resident Children",
                    "agg_func": "sum",
                    "label": "Resident Children",
                },
                {
                    "column": "Resident Students",
                    "agg_func": "sum",
                    "label": "Resident Students",
                },
                {
                    "column": "Citizen Adults",
                    "agg_func": "sum",
                    "label": "Citizen Adults",
                },
                {
                    "column": "Citizen Children",
                    "agg_func": "sum",
                    "label": "Citizen Children",
                },
                {
                    "column": "Citizen Students",
                    "agg_func": "sum",
                    "label": "Citizen Students",
                },
                {"column": "Narok Adults", "agg_func": "sum", "label": "Narok Adults"},
                {
                    "column": "Narok Children",
                    "agg_func": "sum",
                    "label": "Narok Children",
                },
                {
                    "column": "Narok Students",
                    "agg_func": "sum",
                    "label": "Narok Students",
                },
            ],
            **(params_dict.get("guest_group_bar") or {}),
        )
        .call()
    )

    persist_guest_group_bar = (
        persist_text.validate()
        .set_task_instance_id("persist_guest_group_bar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=guest_group_bar,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="guest_group_bar",
            **(params_dict.get("persist_guest_group_bar") or {}),
        )
        .call()
    )

    guest_gate_bar = (
        draw_bar_chart.validate()
        .set_task_instance_id("guest_gate_bar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=guest_pivot,
            category="gate",
            layout_kwargs=None,
            bar_chart_configs=[
                {
                    "column": "Paying Guests",
                    "agg_func": "sum",
                    "label": "Paying Guests",
                    "show_label": True,
                },
                {
                    "column": "Narok County Government(NCG) Guests",
                    "agg_func": "sum",
                    "label": "Narok County Government(NCG) Guests",
                    "show_label": True,
                },
            ],
            **(params_dict.get("guest_gate_bar") or {}),
        )
        .call()
    )

    persist_guest_gate_bar = (
        persist_text.validate()
        .set_task_instance_id("persist_guest_gate_bar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=guest_gate_bar,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="guest_gate_bar",
            **(params_dict.get("persist_guest_gate_bar") or {}),
        )
        .call()
    )

    filter_vehicle = (
        filter_row_values.validate()
        .set_task_instance_id("filter_vehicle")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=tourism_events,
            column="event_type",
            values=["vehicle_entry"],
            **(params_dict.get("filter_vehicle") or {}),
        )
        .call()
    )

    vehicle_gate_bar = (
        draw_bar_chart.validate()
        .set_task_instance_id("vehicle_gate_bar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=filter_vehicle,
            category="gate",
            layout_kwargs=None,
            bar_chart_configs=[
                {
                    "column": "paying",
                    "agg_func": "sum",
                    "label": "Paying Vehicles",
                    "show_label": True,
                },
                {
                    "column": "nonpaying",
                    "agg_func": "sum",
                    "label": "Non-Paying Vehicles",
                    "show_label": True,
                },
                {
                    "column": "sticker",
                    "agg_func": "sum",
                    "label": "Annual Sticker",
                    "show_label": True,
                },
            ],
            **(params_dict.get("vehicle_gate_bar") or {}),
        )
        .call()
    )

    persist_vehicle_gate_bar = (
        persist_text.validate()
        .set_task_instance_id("persist_vehicle_gate_bar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=vehicle_gate_bar,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="vehicle_gate_bar",
            **(params_dict.get("persist_vehicle_gate_bar") or {}),
        )
        .call()
    )

    set_guest_group_title = (
        set_string_var.validate()
        .set_task_instance_id("set_guest_group_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Guest Entry by Group",
            **(params_dict.get("set_guest_group_title") or {}),
        )
        .call()
    )

    guest_group_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("guest_group_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_guest_group_title,
            data=persist_guest_group_bar,
            **(params_dict.get("guest_group_widget") or {}),
        )
        .call()
    )

    set_guest_gate_title = (
        set_string_var.validate()
        .set_task_instance_id("set_guest_gate_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Guest Entry by Gate", **(params_dict.get("set_guest_gate_title") or {})
        )
        .call()
    )

    guest_gate_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("guest_gate_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_guest_gate_title,
            data=persist_guest_gate_bar,
            **(params_dict.get("guest_gate_widget") or {}),
        )
        .call()
    )

    set_vehicle_title = (
        set_string_var.validate()
        .set_task_instance_id("set_vehicle_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Vehicle Entry by Gate", **(params_dict.get("set_vehicle_title") or {})
        )
        .call()
    )

    vehicle_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("vehicle_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_vehicle_title,
            data=persist_vehicle_gate_bar,
            **(params_dict.get("vehicle_widget") or {}),
        )
        .call()
    )

    set_table_title = (
        set_string_var.validate()
        .set_task_instance_id("set_table_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Guest Entry Summary", **(params_dict.get("set_table_title") or {})
        )
        .call()
    )

    guest_table = (
        draw_table.validate()
        .set_task_instance_id("guest_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=guest_summary,
            table_config={"enable_sorting": True},
            widget_id=set_table_title,
            **(params_dict.get("guest_table") or {}),
        )
        .call()
    )

    persist_guest_table = (
        persist_text.validate()
        .set_task_instance_id("persist_guest_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=guest_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="guest_summary_table",
            **(params_dict.get("persist_guest_table") or {}),
        )
        .call()
    )

    table_widget = (
        create_table_widget_single_view.validate()
        .set_task_instance_id("table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_table_title,
            data=persist_guest_table,
            **(params_dict.get("table_widget") or {}),
        )
        .call()
    )

    persist_guest_csv = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_guest_csv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=guest_summary,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="guest_entry_summary",
            filetypes=["csv"],
            sanitize=False,
            **(params_dict.get("persist_guest_csv") or {}),
        )
        .call()
    )

    tourism_report = (
        create_docx.validate()
        .set_task_instance_id("tourism_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=None,
            context={
                "items": [
                    {
                        "item_type": "timerange",
                        "key": "report_date",
                        "value": time_range,
                        "format": "%b %Y",
                    },
                    {
                        "item_type": "image",
                        "key": "guest_entry_bar_chart",
                        "value": persist_guest_group_bar,
                        "screenshot_config": {
                            "wait_for_timeout": 0,
                            "max_concurrent_pages": 2,
                        },
                    },
                    {
                        "item_type": "image",
                        "key": "guest_entry_bar_gate",
                        "value": persist_guest_gate_bar,
                        "screenshot_config": {
                            "wait_for_timeout": 0,
                            "max_concurrent_pages": 2,
                        },
                    },
                    {
                        "item_type": "image",
                        "key": "vehicle_entry_bar",
                        "value": persist_vehicle_gate_bar,
                        "screenshot_config": {
                            "wait_for_timeout": 0,
                            "max_concurrent_pages": 2,
                        },
                    },
                    {"item_type": "table", "key": "data", "value": guest_summary},
                ]
            },
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="mt_tourism_report",
            **(params_dict.get("tourism_report") or {}),
        )
        .call()
    )

    dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                guest_group_widget,
                guest_gate_widget,
                vehicle_widget,
                table_widget,
            ],
            time_range=time_range,
            **(params_dict.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
