# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_bar_chart as draw_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_mt.tasks import mt_guest_entry as mt_guest_entry
from ecoscope_workflows_ext_mt.tasks import mt_guest_entry_pivot as mt_guest_entry_pivot

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "get_timezone": ["time_range"],
        "tourism_events": [],
        "filter_guest": ["tourism_events"],
        "guest_entry_data": ["filter_guest"],
        "guest_summary": ["guest_entry_data"],
        "guest_pivot": ["guest_entry_data"],
        "guest_group_bar": ["guest_summary"],
        "persist_guest_group_bar": ["guest_group_bar"],
        "guest_gate_bar": ["guest_pivot"],
        "persist_guest_gate_bar": ["guest_gate_bar"],
        "filter_vehicle": ["tourism_events"],
        "vehicle_gate_bar": ["filter_vehicle"],
        "persist_vehicle_gate_bar": ["vehicle_gate_bar"],
        "set_guest_group_title": [],
        "guest_group_widget": ["set_guest_group_title", "persist_guest_group_bar"],
        "set_guest_gate_title": [],
        "guest_gate_widget": ["set_guest_gate_title", "persist_guest_gate_bar"],
        "set_vehicle_title": [],
        "vehicle_widget": ["set_vehicle_title", "persist_vehicle_gate_bar"],
        "set_table_title": [],
        "guest_table": ["guest_summary", "set_table_title"],
        "persist_guest_table": ["guest_table"],
        "table_widget": ["set_table_title", "persist_guest_table"],
        "persist_guest_csv": ["guest_summary"],
        "tourism_report": [
            "time_range",
            "persist_guest_group_bar",
            "persist_guest_gate_bar",
            "persist_vehicle_gate_bar",
            "guest_summary",
        ],
        "dashboard": [
            "workflow_details",
            "guest_group_widget",
            "guest_gate_widget",
            "vehicle_widget",
            "table_widget",
            "time_range",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "tourism_events": Node(
            async_task=load_df.validate()
            .set_task_instance_id("tourism_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "deserialize_json": True,
            }
            | (params_dict.get("tourism_events") or {}),
            method="call",
        ),
        "filter_guest": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("filter_guest")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("tourism_events"),
                "column": "event_type",
                "values": [
                    "guest_entry",
                ],
            }
            | (params_dict.get("filter_guest") or {}),
            method="call",
        ),
        "guest_entry_data": Node(
            async_task=mt_guest_entry.validate()
            .set_task_instance_id("guest_entry_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_guest"),
            }
            | (params_dict.get("guest_entry_data") or {}),
            method="call",
        ),
        "guest_summary": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("guest_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("guest_entry_data"),
                "groupby_cols": [
                    "guest_group",
                ],
                "reset_index": True,
                "summary_params": [
                    {
                        "display_name": "Non Resident Adults",
                        "aggregator": "sum",
                        "column": "nra",
                    },
                    {
                        "display_name": "Non Resident Children",
                        "aggregator": "sum",
                        "column": "nrc",
                    },
                    {
                        "display_name": "Non Resident Students",
                        "aggregator": "sum",
                        "column": "nrs",
                    },
                    {
                        "display_name": "Citizen Adults",
                        "aggregator": "sum",
                        "column": "ca",
                    },
                    {
                        "display_name": "Citizen Children",
                        "aggregator": "sum",
                        "column": "cc",
                    },
                    {
                        "display_name": "Citizen Students",
                        "aggregator": "sum",
                        "column": "cs",
                    },
                    {
                        "display_name": "Resident Adults",
                        "aggregator": "sum",
                        "column": "ra",
                    },
                    {
                        "display_name": "Resident Children",
                        "aggregator": "sum",
                        "column": "rc",
                    },
                    {
                        "display_name": "Resident Students",
                        "aggregator": "sum",
                        "column": "rs",
                    },
                    {
                        "display_name": "Narok Adults",
                        "aggregator": "sum",
                        "column": "na",
                    },
                    {
                        "display_name": "Narok Children",
                        "aggregator": "sum",
                        "column": "nc",
                    },
                    {
                        "display_name": "Narok Students",
                        "aggregator": "sum",
                        "column": "ns",
                    },
                ],
            }
            | (params_dict.get("guest_summary") or {}),
            method="call",
        ),
        "guest_pivot": Node(
            async_task=mt_guest_entry_pivot.validate()
            .set_task_instance_id("guest_pivot")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("guest_entry_data"),
            }
            | (params_dict.get("guest_pivot") or {}),
            method="call",
        ),
        "guest_group_bar": Node(
            async_task=draw_bar_chart.validate()
            .set_task_instance_id("guest_group_bar")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("guest_summary"),
                "category": "guest_group",
                "layout_kwargs": None,
                "bar_chart_configs": [
                    {
                        "column": "Non Resident Adults",
                        "agg_func": "sum",
                        "label": "Non Resident Adults",
                    },
                    {
                        "column": "Non Resident Children",
                        "agg_func": "sum",
                        "label": "Non Resident Children",
                    },
                    {
                        "column": "Non Resident Students",
                        "agg_func": "sum",
                        "label": "Non Resident Students",
                    },
                    {
                        "column": "Resident Adults",
                        "agg_func": "sum",
                        "label": "Resident Adults",
                    },
                    {
                        "column": "Resident Children",
                        "agg_func": "sum",
                        "label": "Resident Children",
                    },
                    {
                        "column": "Resident Students",
                        "agg_func": "sum",
                        "label": "Resident Students",
                    },
                    {
                        "column": "Citizen Adults",
                        "agg_func": "sum",
                        "label": "Citizen Adults",
                    },
                    {
                        "column": "Citizen Children",
                        "agg_func": "sum",
                        "label": "Citizen Children",
                    },
                    {
                        "column": "Citizen Students",
                        "agg_func": "sum",
                        "label": "Citizen Students",
                    },
                    {
                        "column": "Narok Adults",
                        "agg_func": "sum",
                        "label": "Narok Adults",
                    },
                    {
                        "column": "Narok Children",
                        "agg_func": "sum",
                        "label": "Narok Children",
                    },
                    {
                        "column": "Narok Students",
                        "agg_func": "sum",
                        "label": "Narok Students",
                    },
                ],
            }
            | (params_dict.get("guest_group_bar") or {}),
            method="call",
        ),
        "persist_guest_group_bar": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_guest_group_bar")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("guest_group_bar"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "guest_group_bar",
            }
            | (params_dict.get("persist_guest_group_bar") or {}),
            method="call",
        ),
        "guest_gate_bar": Node(
            async_task=draw_bar_chart.validate()
            .set_task_instance_id("guest_gate_bar")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("guest_pivot"),
                "category": "gate",
                "layout_kwargs": None,
                "bar_chart_configs": [
                    {
                        "column": "Paying Guests",
                        "agg_func": "sum",
                        "label": "Paying Guests",
                        "show_label": True,
                    },
                    {
                        "column": "Narok County Government(NCG) Guests",
                        "agg_func": "sum",
                        "label": "Narok County Government(NCG) Guests",
                        "show_label": True,
                    },
                ],
            }
            | (params_dict.get("guest_gate_bar") or {}),
            method="call",
        ),
        "persist_guest_gate_bar": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_guest_gate_bar")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("guest_gate_bar"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "guest_gate_bar",
            }
            | (params_dict.get("persist_guest_gate_bar") or {}),
            method="call",
        ),
        "filter_vehicle": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("filter_vehicle")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("tourism_events"),
                "column": "event_type",
                "values": [
                    "vehicle_entry",
                ],
            }
            | (params_dict.get("filter_vehicle") or {}),
            method="call",
        ),
        "vehicle_gate_bar": Node(
            async_task=draw_bar_chart.validate()
            .set_task_instance_id("vehicle_gate_bar")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("filter_vehicle"),
                "category": "gate",
                "layout_kwargs": None,
                "bar_chart_configs": [
                    {
                        "column": "paying",
                        "agg_func": "sum",
                        "label": "Paying Vehicles",
                        "show_label": True,
                    },
                    {
                        "column": "nonpaying",
                        "agg_func": "sum",
                        "label": "Non-Paying Vehicles",
                        "show_label": True,
                    },
                    {
                        "column": "sticker",
                        "agg_func": "sum",
                        "label": "Annual Sticker",
                        "show_label": True,
                    },
                ],
            }
            | (params_dict.get("vehicle_gate_bar") or {}),
            method="call",
        ),
        "persist_vehicle_gate_bar": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_vehicle_gate_bar")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("vehicle_gate_bar"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "vehicle_gate_bar",
            }
            | (params_dict.get("persist_vehicle_gate_bar") or {}),
            method="call",
        ),
        "set_guest_group_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_guest_group_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Guest Entry by Group",
            }
            | (params_dict.get("set_guest_group_title") or {}),
            method="call",
        ),
        "guest_group_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("guest_group_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_guest_group_title"),
                "data": DependsOn("persist_guest_group_bar"),
            }
            | (params_dict.get("guest_group_widget") or {}),
            method="call",
        ),
        "set_guest_gate_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_guest_gate_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Guest Entry by Gate",
            }
            | (params_dict.get("set_guest_gate_title") or {}),
            method="call",
        ),
        "guest_gate_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("guest_gate_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_guest_gate_title"),
                "data": DependsOn("persist_guest_gate_bar"),
            }
            | (params_dict.get("guest_gate_widget") or {}),
            method="call",
        ),
        "set_vehicle_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_vehicle_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Vehicle Entry by Gate",
            }
            | (params_dict.get("set_vehicle_title") or {}),
            method="call",
        ),
        "vehicle_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("vehicle_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_vehicle_title"),
                "data": DependsOn("persist_vehicle_gate_bar"),
            }
            | (params_dict.get("vehicle_widget") or {}),
            method="call",
        ),
        "set_table_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_table_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Guest Entry Summary",
            }
            | (params_dict.get("set_table_title") or {}),
            method="call",
        ),
        "guest_table": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("guest_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("guest_summary"),
                "columns": None,
                "table_config": {
                    "enable_sorting": True,
                },
                "widget_id": DependsOn("set_table_title"),
            }
            | (params_dict.get("guest_table") or {}),
            method="call",
        ),
        "persist_guest_table": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_guest_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("guest_table"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "guest_summary_table",
            }
            | (params_dict.get("persist_guest_table") or {}),
            method="call",
        ),
        "table_widget": Node(
            async_task=create_table_widget_single_view.validate()
            .set_task_instance_id("table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_table_title"),
                "data": DependsOn("persist_guest_table"),
            }
            | (params_dict.get("table_widget") or {}),
            method="call",
        ),
        "persist_guest_csv": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_guest_csv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("guest_summary"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "guest_entry_summary",
                "filetypes": [
                    "csv",
                ],
                "sanitize": False,
            }
            | (params_dict.get("persist_guest_csv") or {}),
            method="call",
        ),
        "tourism_report": Node(
            async_task=create_docx.validate()
            .set_task_instance_id("tourism_report")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupers": None,
                "context": {
                    "items": [
                        {
                            "item_type": "timerange",
                            "key": "report_date",
                            "value": DependsOn("time_range"),
                            "format": "%b %Y",
                        },
                        {
                            "item_type": "image",
                            "key": "guest_entry_bar_chart",
                            "value": DependsOn("persist_guest_group_bar"),
                            "screenshot_config": {
                                "wait_for_timeout": 0,
                                "max_concurrent_pages": 2,
                            },
                        },
                        {
                            "item_type": "image",
                            "key": "guest_entry_bar_gate",
                            "value": DependsOn("persist_guest_gate_bar"),
                            "screenshot_config": {
                                "wait_for_timeout": 0,
                                "max_concurrent_pages": 2,
                            },
                        },
                        {
                            "item_type": "image",
                            "key": "vehicle_entry_bar",
                            "value": DependsOn("persist_vehicle_gate_bar"),
                            "screenshot_config": {
                                "wait_for_timeout": 0,
                                "max_concurrent_pages": 2,
                            },
                        },
                        {
                            "item_type": "table",
                            "key": "data",
                            "value": DependsOn("guest_summary"),
                        },
                    ],
                },
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "mt_tourism_report",
            }
            | (params_dict.get("tourism_report") or {}),
            method="call",
        ),
        "dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("guest_group_widget"),
                    DependsOn("guest_gate_widget"),
                    DependsOn("vehicle_widget"),
                    DependsOn("table_widget"),
                ],
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
